// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";

// Try to load dotenv in a safe way
try {
  // Dynamic import to avoid linting issues
  await import("dotenv/config");
} catch {
  // dotenv not available during prisma generate, that's ok
  console.log('Dotenv not available during config load');
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: `mysql://${process.env.DATABASE_USER || 'root'}:${process.env.DATABASE_PASSWORD || 'password'}@${process.env.DATABASE_HOST || 'localhost'}:${process.env.DATABASE_PORT || '3306'}/${process.env.DATABASE_NAME || 'translations'}`,
  },
});
